name: Build and Test

on:
  push:
    branches: [ main ]
    paths:
    - 'workouts/**.csv'
    - '.github/**'

jobs:
  build:
    name: Gist Box

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout private health repo
      uses: actions/checkout@v2
      with:
        repository: mribrgr/health
        token: ${{ secrets.HEALTH_REPO_TOKEN }}
        path: health
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.1
    - name: Cache gems
      uses: actions/cache@v4.2.0
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Install gems
      run: |
        gem install octokit
    - name: Run script to update gist 
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        ruby .github/scripts/hadge.rb -t $GH_TOKEN -g $GIST_ID health/workouts/$(date +%Y).csv